import { action, adminResource, column, field, filter, lens } from '@foobarjs/framework';

const statusBadges = {
  draft: 'secondary',
  pending: 'warning',
  paid: 'success',
  fulfilled: 'azure',
  cancelled: 'danger',
  refunded: 'purple',
};

export default adminResource('Order', {
  label: 'Orders',
  display: 'number',
  list: [
    column('number').searchable().sortable(),
    column('customer').relationship({ perPage: 25, placeholder: 'Search customers' }),
    column('email').searchable().sortable(),
    column('status').badge(statusBadges).sortable(),
    column('total').money('USD').sortable(),
    column('createdAt').date().sortable().label('Placed'),
  ],
  form: [
    column('customer').relationship({ perPage: 25, placeholder: 'Search customers' }),
    column('number').readonly().help('Generated by the checkout service.'),
    column('email').placeholder('buyer@example.com'),
    column('subtotal'),
    column('tax'),
    column('shipping'),
    column('total'),
    column('status').readonly().help('Use actions to change order state.'),
  ],
  detail: [
    column('number'),
    column('customer'),
    column('email'),
    column('status').badge(statusBadges),
    column('subtotal').money('USD'),
    column('tax').money('USD'),
    column('shipping').money('USD'),
    column('total').money('USD'),
    column('createdAt').date().label('Placed'),
  ],
  filters: [
    filter.enum('status').query((query, value) => query.where('status', value)),
    filter.relationship('customer', { perPage: 25 }).placeholder('Search customers'),
    filter.dateRange('createdAt'),
  ],
  lenses: [
    lens('pending', {
      label: 'Pending',
      query: query => query.pending(),
    }),
    lens('paid', {
      label: 'Paid',
      query: query => query.paid(),
    }),
    lens('highValue', {
      label: 'High value',
      query: query => query.highValue(),
      columns: [
        column('number').searchable().sortable(),
        column('email').searchable().sortable(),
        column('total').money('USD').sortable(),
        column('status').badge(statusBadges),
      ],
    }),
  ],
  actions: [
    action('markPaid', ({ record }) => {
      record.update({ status: 'paid' });
    }).row().label('Mark paid').confirm('Mark this order as paid?'),
    action('fulfill', ({ record }) => {
      record.update({ status: 'fulfilled' });
    }).row().label('Fulfill').primary().confirm('Mark this order fulfilled?'),
    action('cancelWithReason', ({ data, record }) => {
      record.update({ status: 'cancelled' });
      return { notice: `Cancelled with reason: ${data.reason}` };
    }).row().label('Cancel with reason').danger().form({
      reason: field.text().required().max(500),
    }),
    action('cancelSelected', ({ records }) => {
      for (const record of records) record.update({ status: 'cancelled' });
    }).bulk().label('Cancel selected').danger().confirm('Cancel the selected orders?'),
  ],
  relationships: [
    { name: 'items', label: 'Line items', perPage: 10 },
  ],
});
