export async function up(schema) {
  schema.create("users", table => {
    table.id()
    table.string("name").notNullable()
    table.string("email").notNullable().unique()
    table.string("password").notNullable()
    table.string("role").default("admin")
    table.string("status").default("active")
    table.timestamps()
  })
  schema.create("categories", table => {
    table.id()
    table.string("name").notNullable()
    table.string("slug").notNullable().unique()
    table.text("description")
    table.string("status").default("active")
    table.timestamps()
  })
  schema.create("customers", table => {
    table.id()
    table.string("first_name").notNullable()
    table.string("last_name").notNullable()
    table.string("email").notNullable().unique()
    table.string("phone")
    table.string("status").default("active")
    table.timestamps()
  })
  schema.create("products", table => {
    table.id()
    table.string("name").notNullable()
    table.string("slug").notNullable().unique()
    table.string("sku").notNullable().unique()
    table.text("description")
    table.string("image_path")
    table.decimal("price").notNullable()
    table.integer("inventory").notNullable().default(0)
    table.string("status").default("active")
    table.foreignId("category_id").references("categories.id")
    table.timestamps()
  })
  schema.create("orders", table => {
    table.id()
    table.string("number").notNullable().unique()
    table.string("email").notNullable()
    table.string("status").default("pending")
    table.decimal("subtotal").notNullable()
    table.decimal("tax").notNullable().default(0)
    table.decimal("shipping").notNullable().default(0)
    table.decimal("total").notNullable()
    table.foreignId("customer_id").references("customers.id")
    table.timestamps()
  })
  schema.create("order_items", table => {
    table.id()
    table.foreignId("order_id").references("orders.id")
    table.foreignId("product_id").references("products.id")
    table.string("name").notNullable()
    table.string("sku").notNullable()
    table.integer("quantity").notNullable()
    table.decimal("unit_price").notNullable()
    table.decimal("total").notNullable()
    table.timestamps()
  })
  schema.create("pages", table => {
    table.id()
    table.string("title").notNullable()
    table.string("slug").notNullable().unique()
    table.text("body")
    table.string("status").default("draft")
    table.timestamps()
  })
}

export async function down(schema) {
  schema.dropIfExists("order_items")
  schema.dropIfExists("orders")
  schema.dropIfExists("products")
  schema.dropIfExists("customers")
  schema.dropIfExists("categories")
  schema.dropIfExists("pages")
  schema.dropIfExists("users")
}
